name: 'Execução agendada'

on:
  schedule:
    - cron: '30 7 * * 3'

jobs:
  e2e-tests:

    runs-on: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Testes E2E (end-to-end)
        run: npx cypress run

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./cypress/reports